<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="350138591650T" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="07 Sep 2018 16:31:31 GMT" time="0.054" errors="0">
  <testcase name="test3" time="0.012" classname="demo.TestNGRetryFailDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.TestNGRetryFailDemo.test3(TestNGRetryFailDemo.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.002" classname="demo.TestNGRetryFailDemo"/>
  <testcase name="test1" time="0.0" classname="demo.TestNGRetryFailDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
